export const modalStyles = {
	content: {
		width: '580px',
		height: '580px',
		display: 'inline-block',
		justifyContent: 'center',
		alignItems: 'center',
		backgroundColor: 'rgb(0, 183, 255)',
		top: '50%',
		left: '50%',
		right: 'auto',
		bottom: 'auto',
		marginRight: '-50%',
		transform: 'translate(-50%, -50%)',
		borderRadius: '5px',
		border: '1px solid aqua',
		overflow: 'hidden',
	},
}

export const dialogStyles = {
	content: {
		width: '300px',
		height: '130px',
		display: 'inline-block',
		justifyContent: 'center',
		alignItems: 'center',
		backgroundColor: '#0b537c',
		top: '50%',
		left: '50%',
		right: 'auto',
		bottom: 'auto',
		marginRight: '-50%',
		transform: 'translate(-50%, -50%)',
		borderRadius: '5px',
		border: '1px solid aqua',
		overflow: 'hidden',
		padding: '0px',
	},
}

export const progressStyles = {
	content: {
		width: '580px',
		height: '280px',
		display: 'inline-block',
		justifyContent: 'right',
		alignItems: 'center',
		backgroundColor: 'rgb(0, 183, 255)',
		top: '50%',
		left: '50%',
		right: 'auto',
		bottom: 'auto',
		marginRight: '-50%',
		transform: 'translate(-50%, -50%)',
		borderRadius: '5px',
		border: '1px solid aqua',
		overflow: 'hidden',
	},
}

export const hourglassStyle = {
	content: {
		width: '580px',
		height: '580px',
		display: 'flex',
		justifyContent: 'center',
		alignItems: 'center',
		backgroundColor: 'rgb(255, 255, 255, 0)',
		top: '50%',
		left: '50%',
		right: 'auto',
		bottom: 'auto',
		marginRight: '-50%',
		transform: 'translate(-50%, -50%)',
		overflow: 'hidden',
		border: 0,
	},
}

export const tableStyles = {
	content: {
		width: '580px',
		height: '600px',
		display: 'inline-block',
		justifyContent: 'center',
		alignItems: 'center',
		backgroundColor: '#0b537c' /*'rgb(0, 183, 255)'*/,
		top: '50%',
		left: '50%',
		right: 'auto',
		bottom: 'auto',
		marginRight: '-50%',
		transform: 'translate(-50%, -50%)',
		borderRadius: '5px',
		border: '1px solid aqua',
		overflow: 'hidden',
		padding: '0px',
	},
}
